{"name": "test_login_incorrect_credentials", "status": "broken", "statusDetails": {"message": "AttributeError: type object 'Locator' has no attribute 'passwor'. Did you mean: 'password'?", "trace": "setup = (0.1, <POM.Functions.Functions object at 0x00000230F373BBE0>)\n\n    def test_login_incorrect_credentials(setup):\n        t, f = setup\n    \n        # Ingresa un correo y una contraseÃ±a incorrectos\n        f.validate_and_send_keys(\"xpath\", Locator.email, \"admin@asdrome.com\", t)\n>       f.validate_and_send_keys(\"xpath\", Locator.passwor, \"admidan\", t)\nE       AttributeError: type object 'Locator' has no attribute 'passwor'. Did you mean: 'password'?\n\ntest_login_fixture_allure.py:112: AttributeError"}, "attachments": [{"name": "stdout", "source": "3435df82-b41e-4d85-a1d9-08ff09292b49-attachment.txt", "type": "text/plain"}], "start": 1722535616365, "stop": 1722535616584, "uuid": "83ee3c2a-961a-4cb4-8cae-5cb0df43d81d", "historyId": "0e5453702b8ecd0caf1a7b202ba64d19", "testCaseId": "0e5453702b8ecd0caf1a7b202ba64d19", "fullName": "test_login_fixture_allure#test_login_incorrect_credentials", "labels": [{"name": "suite", "value": "test_login_fixture_allure"}, {"name": "host", "value": "ASUS"}, {"name": "thread", "value": "9468-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_fixture_allure"}]}